version: "3.1"
services:
  postgres:
    build: ./db
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
    volumes:
      - ./db:/var/lib/db
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
  client:
    build: ./client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    depends_on:
      - server
