version: "3.3"

services:
  frontend:
    build: frontend
    # local port : container port
    ports:
      - "3000:3000"
    networks:
      - wish-network
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://localhost:3001

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      # local folder where database files are : container folder
      - ./db:/var/lib/postgresql/data/docker-project
    networks:
      - wish-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: backend
    ports:
      - "3001:3000"
    networks:
      - wish-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/db
    depends_on:
      db:
        condition: service_healthy

# set-up network for container communication
networks:
  wish-network:
    driver: bridge
